name: Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-carbon-apimgt:
    name: Build carbon-apimgt
    runs-on: ubuntu-latest
    outputs:
      carbon-apimgt-version: ${{ steps.set-carbon-apimgt-version.outputs.carbon-apimgt-version }}
    steps:
      - name: Set hostname
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          repository: wso2/carbon-apimgt
          ref: refs/heads/master
          fetch-depth: '10'
          path: carbon-apimgt
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.16+8
          distribution: 'temurin'
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build carbon-apimgt with tests, skipping AspectJ
        run: mvn clean install --file carbon-apimgt/pom.xml -Dskip.aspectj=true
      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unit_tests
      - name: Set carbon.apimgt.version
        id: set-carbon-apimgt-version
        run: echo "carbon-apimgt-version=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_OUTPUT
  build-product-apim:
    name: Build product-apim
    runs-on: ubuntu-latest
    needs: build-carbon-apimgt
    steps:
      - name: Set hostname
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          repository: wso2/product-apim
          ref: refs/heads/master
          fetch-depth: '10'
          path: product-apim
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11.0.16+8
          distribution: 'temurin'
      - uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2
          restore-keys: ${{ runner.os }}-m2
      - name: Build product-apim without tests
        run: mvn clean install -Dcarbon.apimgt.version=${{needs.build-carbon-apimgt.outputs.carbon-apimgt-version}} -fae --file product-apim/pom.xml -Dmaven.test.skip=true
  run-integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: build-product-apim
    steps:
      - name: Set hostname
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
  run-ui-test:
    name: Run ui tests
    runs-on: ubuntu-latest
    needs: build-product-apim
    steps:
      - name: Set hostname
        run: sudo echo "127.0.0.1 $(hostname)" | sudo tee -a /etc/hosts
