name: Test outputs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  set-output:
    name: Set output
    runs-on: ubuntu-latest
    outputs:
      carbon-apimgt-version: ${{ steps.set-carbon-apimgt-version.outputs.carbon-apimgt-version }}
    steps:
      - name: Set output
        id: set-carbon-apimgt-version
        run: echo "carbon-apimgt-version=1.2.3" >> $GITHUB_OUTPUT
  get-output:
    name: Get output
    runs-on: ubuntu-latest
    needs: set-output
    steps:
      - name: Get output
        run: echo "carbon-apimgt-version=${{ needs.set-output.outputs.carbon-apimgt-version }}"
