name: Test uploading/downloading artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: binodmx/helasentilex
          ref: refs/heads/master
          fetch-depth: '10'
          path: helasentilex
      - name: Get files
        run: ls
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: README.md
          path: helasentilex/README.md
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: hello.txt
      - name: Read file
        run: cat README.md
