name: Test uploading/downloading artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "hello binod" > hello.txt
      - name: Upload file
        uses: actions/upload-artifact@v2
        with:
          name: hello.txt
          path: hello.txt
  job2:
    name: Job 2
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: hello.txt
      - name: Read file
        run: cat hello.txt
